Repository renatak12/construct, pull requests merged in 2023-05, with the labels that each got.

#20 Criando Doc arquitetural
  docs/doc-arquitetural.md
  docs/images/modelo_arq.jpg
Labels: documentation

#25 Update doc-visao.md #13
  docs/doc-visao.md
Labels: documentation

#33 Detalhando user story US03. #14
  docs/doc-user-stories.md
Labels: documentation

#34 Testes de Aceitação doc-user-stories.md #14
  docs/doc-user-stories.md
Labels: documentation

#35 objetivo do projeto doc-termo-abertura.md #17
  docs/doc-termo-abertura.md
Labels: documentation

#37 Update doc-termo-abertura.md #17
  docs/doc-termo-abertura.md
Labels: documentation

#48 40 documento arquitetural do sistema
  docs/doc-arquitetural.md
Labels: documentation

#51 Add diagrama de implementação. #40
  docs/images/diagrama_implantacao.png
Labels: img

#52 Criando doc. inicial de testes do sistema. #42
  docs/doc-tests-us.md
Labels: documentation

#53 componentes-implementacao doc-arquitetural.md #40
  docs/doc-arquitetural.md
Labels: documentation

#56 Atualização do Documento APF #41
  docs/doc-apf.md
Labels: documentation

#57 Adição das US04 e US05 #43
  docs/doc-user-stories.md
Labels: documentation

#58 implementação US02 e US03 #45
  construct_/estoque/__init__.py
  construct_/estoque/__pycache__/__init__.cpython-311.pyc
  construct_/estoque/__pycache__/admin.cpython-311.pyc
  construct_/estoque/__pycache__/apps.cpython-311.pyc
  construct_/estoque/__pycache__/forms.cpython-311.pyc
  construct_/estoque/__pycache__/models.cpython-311.pyc
  construct_/estoque/__pycache__/urls.cpython-311.pyc
  construct_/estoque/__pycache__/views.cpython-311.pyc
  construct_/estoque/admin.py
  construct_/estoque/apps.py
  construct_/estoque/forms.py
  construct_/estoque/migrations/0001_initial.py
  construct_/estoque/migrations/__init__.py
  construct_/estoque/migrations/__pycache__/0001_initial.cpython-311.pyc
  construct_/estoque/migrations/__pycache__/__init__.cpython-311.pyc
  construct_/estoque/models.py
  construct_/estoque/templates/add_produto.html
  construct_/estoque/templates/produto.html
  construct_/estoque/templatetags/__init__.py
  construct_/estoque/templatetags/__pycache__/__init__.cpython-311.pyc
  construct_/estoque/templatetags/__pycache__/filters.cpython-311.pyc
  construct_/estoque/templatetags/filters.py
  construct_/estoque/tests.py
  construct_/estoque/urls.py
  construct_/estoque/views.py
Labels: enhancement

#59 Atualizando doc com teste de login. #42
  docs/doc-tests-us.md
Labels: documentation
